#!/usr/bin/env python3
"""Generate a Code Snippets one-time writer for Rank Math SEO metadata."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


REQUIRED = {"id", "object_type", "seo_title", "seo_description", "focus_keyword"}
POST_TYPES = {"post", "page", "product"}
TERM_TYPES = {"term", "category", "post_tag", "product_cat", "product_tag"}


def load_mapping(path: Path) -> list[dict[str, Any]]:
    try:
        data = json.loads(path.read_text(encoding="utf-8-sig"))
    except FileNotFoundError:
        raise SystemExit(f"Mapping file not found: {path}")
    except json.JSONDecodeError as exc:
        raise SystemExit(f"Invalid JSON: {exc}")
    if isinstance(data, dict):
        data = data.get("items") or data.get("mapping") or []
    if not isinstance(data, list):
        raise SystemExit("Mapping JSON must be a list or an object with items/mapping list.")
    return data


def validate_item(item: dict[str, Any], index: int) -> list[str]:
    errors: list[str] = []
    missing = sorted(REQUIRED - set(item))
    if missing:
        errors.append(f"item[{index}] missing: {', '.join(missing)}")
    object_type = str(item.get("object_type", "")).lower()
    if object_type not in POST_TYPES | TERM_TYPES:
        errors.append(f"item[{index}] invalid object_type: {object_type}")
    try:
        int(item.get("id"))
    except (TypeError, ValueError):
        errors.append(f"item[{index}] id must be integer-like")
    for key in ("seo_title", "seo_description", "focus_keyword"):
        if not str(item.get(key, "")).strip():
            errors.append(f"item[{index}] {key} is empty")
    return errors


def normalize(items: list[dict[str, Any]]) -> list[dict[str, Any]]:
    errors: list[str] = []
    normalized: list[dict[str, Any]] = []
    seen: set[tuple[str, int]] = set()
    for index, item in enumerate(items):
        errors.extend(validate_item(item, index))
        if errors:
            continue
        object_type = str(item["object_type"]).lower()
        item_id = int(item["id"])
        key = (object_type, item_id)
        if key in seen:
            errors.append(f"duplicate mapping for {object_type}:{item_id}")
            continue
        seen.add(key)
        normalized.append(
            {
                "id": item_id,
                "object_type": object_type,
                "seo_title": str(item["seo_title"]).strip(),
                "seo_description": str(item["seo_description"]).strip(),
                "focus_keyword": str(item["focus_keyword"]).strip(),
                "robots": item.get("robots", "index,follow"),
                "schema_type": item.get("schema_type", ""),
                "source_evidence": item.get("source_evidence", ""),
                "overwrite": bool(item.get("overwrite", False)),
            }
        )
    if errors:
        raise SystemExit("Mapping validation failed:\n- " + "\n- ".join(errors))
    return normalized


def php_string(value: Any) -> str:
    return json.dumps(str(value), ensure_ascii=False)


def generate_php(items: list[dict[str, Any]], delete_after: bool) -> str:
    encoded = json.dumps(items, ensure_ascii=False, indent=2)
    delete_note = "true" if delete_after else "false"
    return f"""<?php
/**
 * one_time_writer / Rank Math SEO Meta Writer
 * Generated by scripts/rank_math_meta_writer.py.
 * Run once through Code Snippets, verify results, then disable and delete this snippet.
 */
add_action('admin_init', function () {{
    if (!current_user_can('manage_options')) {{
        return;
    }}

    $done_key = 'wasb_rank_math_meta_writer_done_' . md5(__FILE__);
    if (get_option($done_key)) {{
        return;
    }}

    $items = json_decode({php_string(encoded)}, true);
    $report = array(
        'written' => array(),
        'skipped' => array(),
        'failed' => array(),
    );

    foreach ($items as $item) {{
        $id = isset($item['id']) ? absint($item['id']) : 0;
        $object_type = isset($item['object_type']) ? sanitize_key($item['object_type']) : '';
        $overwrite = !empty($item['overwrite']);

        if (!$id || !$object_type) {{
            $report['failed'][] = array('id' => $id, 'reason' => 'missing_id_or_type');
            continue;
        }}

        $title = sanitize_text_field($item['seo_title'] ?? '');
        $description = sanitize_text_field($item['seo_description'] ?? '');
        $focus = sanitize_text_field($item['focus_keyword'] ?? '');
        $robots = sanitize_text_field($item['robots'] ?? 'index,follow');

        if (!$title || !$description || !$focus) {{
            $report['failed'][] = array('id' => $id, 'reason' => 'missing_required_meta');
            continue;
        }}

        if (in_array($object_type, array('post', 'page', 'product'), true)) {{
            if (!get_post($id)) {{
                $report['failed'][] = array('id' => $id, 'type' => $object_type, 'reason' => 'post_not_found');
                continue;
            }}

            $existing_title = get_post_meta($id, '_rank_math_title', true);
            if ($existing_title && !$overwrite) {{
                $report['skipped'][] = array('id' => $id, 'type' => $object_type, 'reason' => 'existing_meta');
                continue;
            }}

            update_post_meta($id, '_rank_math_title', $title);
            update_post_meta($id, '_rank_math_description', $description);
            update_post_meta($id, '_rank_math_focus_keyword', $focus);
            update_post_meta($id, '_rank_math_robots', $robots);
            if (!empty($item['schema_type'])) {{
                update_post_meta($id, '_rank_math_rich_snippet', sanitize_text_field($item['schema_type']));
            }}
            $report['written'][] = array('id' => $id, 'type' => $object_type);
            continue;
        }}

        if (in_array($object_type, array('term', 'category', 'post_tag', 'product_cat', 'product_tag'), true)) {{
            $term = get_term($id);
            if (!$term || is_wp_error($term)) {{
                $report['failed'][] = array('id' => $id, 'type' => $object_type, 'reason' => 'term_not_found');
                continue;
            }}

            $existing_title = get_term_meta($id, 'rank_math_title', true);
            if ($existing_title && !$overwrite) {{
                $report['skipped'][] = array('id' => $id, 'type' => $object_type, 'reason' => 'existing_meta');
                continue;
            }}

            update_term_meta($id, 'rank_math_title', $title);
            update_term_meta($id, 'rank_math_description', $description);
            update_term_meta($id, 'rank_math_focus_keyword', $focus);
            update_term_meta($id, 'rank_math_robots', $robots);
            $report['written'][] = array('id' => $id, 'type' => $object_type);
            continue;
        }}

        $report['failed'][] = array('id' => $id, 'type' => $object_type, 'reason' => 'unsupported_type');
    }}

    update_option($done_key, array(
        'time' => current_time('mysql'),
        'report' => $report,
        'delete_after_verification' => {delete_note},
    ), false);

    error_log('WASB Rank Math meta writer report: ' . wp_json_encode($report));
}});
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("mapping", type=Path, help="JSON list of SEO metadata mapping items")
    parser.add_argument("--output", type=Path, help="Write PHP snippet to file")
    parser.add_argument("--keep-after-run", action="store_true", help="Do not mark snippet for deletion after verification")
    args = parser.parse_args()

    items = normalize(load_mapping(args.mapping))
    php = generate_php(items, delete_after=not args.keep_after_run)
    if args.output:
        args.output.write_text(php, encoding="utf-8")
        print(f"Wrote {args.output} with {len(items)} mapping items.")
    else:
        print(php)
    return 0


if __name__ == "__main__":
    sys.exit(main())
